name: Security Scan test

on:
  push:
    branches: master
  workflow_dispatch:  # Allow manual triggers
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
          chmod +x ./snyk
          sudo mv ./snyk /usr/local/bin/
      
            # Run Snyk to check for code vulnerabilities and generate report
      - name: Snyk Code Test
        run: snyk code test --all-projects --report --report --detection-depth=10 --project-name="${{ github.event.repository.name }}" --target-name="${{ github.repository }}"
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk to check for dependencies vulnerabilities and generate report
      - name: Snyk Dependencies Test
        run: snyk test --all-projects --report --report --detection-depth=10 --project-name="${{ github.event.repository.name }}" --target-name="${{ github.repository }}"
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Monitor the project in Snyk
     # - name: Monitor Project in Snyk
      #  uses: snyk/actions/node@master
       # with:
        #  command: monitor
         # args: --project-name=github/${{ github.repository }}
       # env:
        #  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}     
