name: Security Scan test1

on:
  push:
    branches: master
  workflow_dispatch:  # Allow manual triggers
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
          chmod +x ./snyk
          sudo mv ./snyk /usr/local/bin/
      
            # Run Snyk to check for code vulnerabilities and generate report
      - name: Snyk Code Test
        run: snyk code test
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Restore Dependencies for All Projects
        run:  dotnet restore dotnet/WebApp45/WebApp45 && dotnet restore ./dotnetcore/WebAppRazor/WebAppRazor && cd angular/simple-app && npm install && cd ../.. && cd nodejs/simple-app && npm install && cd ../.. && cd angularjs/simple-app && npm install && cd ../..
      
      - name: Snyk Dependencies Test
        run: snyk test --all-projects
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Snyk Code Test Angular
        run: snyk code test ./angular/simple-app
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code Test Angularjs
        run: snyk code test ./angularjs/simple-app
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code Test dotnetcore
        run: snyk code test ./dotnetcore/WebAppRazor
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Restore Dependencies
        run: dotnet restore ./dotnetcore/WebAppRazor/WebAppRazor

      - name: Snyk Test dotnetcore
        run: snyk test ./dotnetcore/WebAppRazor/WebAppRazor
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 

      # Monitor the project in Snyk
     # - name: Monitor Project in Snyk
      #  uses: snyk/actions/node@master
       # with:
        #  command: monitor
         # args: --project-name=github/${{ github.repository }}
       # env:
        #  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}     
